### ISSUE TITLE
React peer dependency

### ISSUE THREAD

**Issue by mhisham744** [syt123450/react-giojs#2]
I would like to use this library in an app which requires react 16.3 or later. 

Would it be possible to make react and react-dom as peer dependencies?

Thanks!

**Comment by syt123450** [comment]
Yes, you can use react and react-dom separately in your react app, I write several demo, in the hello world demo [links](https://github.com/syt123450/react-giojs/tree/master/examples/00_helloworld), I use react and react-dom as peer dependencies.  In this [js file](https://github.com/syt123450/react-giojs/blob/master/examples/00_helloworld/helloworld.js), import react and react-dom separately.
